### ISSUE TITLE
Many errors..

### ISSUE THREAD

**Issue by snekROmonoro** [Danny-Dasilva/CycleTLS#235]
### Description

Idk if I should panic and make this issue, but I will anyways. Basically my app is multi-threaded and making requests from the same client. I am not using a worker pool so that might be an issue, even though I am not sure.

go version go1.19.4 windows/amd64

### Node Version

None

### Golang Version

Other

### Relevant Log Output

```shell
goroutine 140421 [IO wait, 5 minutes]:
internal/poll.runtime_pollWait(0x252ec2d0248, 0x72)
        C:/Program Files/Go/src/runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0xa?, 0x21e?, 0x0)
        C:/Program Files/Go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.execIO(0xc039347918, 0xeffe60)
        C:/Program Files/Go/src/internal/poll/fd_windows.go:175 +0xe5
internal/poll.(*FD).Read(0xc039347900, {0xc0305e6380, 0xd80, 0xd80})
        C:/Program Files/Go/src/internal/poll/fd_windows.go:441 +0x26b
net.(*netFD).Read(0xc039347900, {0xc0305e6380?, 0x21e?, 0xc0305e6edd?})
        C:/Program Files/Go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc01f3460a8, {0xc0305e6380?, 0x8?, 0x29d?})
        C:/Program Files/Go/src/net/net.go:183 +0x45
github.com/Danny-Dasilva/utls.(*atLeastReader).Read(0xc002a2e168, {0xc0305e6380?, 0x0?, 0x8?})
        C:/Users/snek/go/pkg/mod/github.com/!danny-!dasilva/utls@v0.0.0-20220604023528-30cb107b834e/conn.go:780 +0x3d
bytes.(*Buffer).ReadFrom(0xc020ab25d8, {0xf83500, 0xc002a2e168})
        C:/Program Files/Go/src/bytes/buffer.go:202 +0x98
github.com/Danny-Dasilva/utls.(*Conn).readFromUntil(0xc020ab2380, {0x252e87f96c8?, 0xc01f3460a8}, 0x223?)
        C:/Users/snek/go/pkg/mod/github.com/!danny-!dasilva/utls@v0.0.0-20220604023528-30cb107b834e/conn.go:802 +0xe5
github.com/Danny-Dasilva/utls.(*Conn).readRecordOrCCS(0xc020ab2380, 0x0)
        C:/Users/snek/go/pkg/mod/github.com/!danny-!dasilva/utls@v0.0.0-20220604023528-30cb107b834e/conn.go:609 +0x10d
github.com/Danny-Dasilva/utls.(*Conn).readRecord(...)
        C:/Users/snek/go/pkg/mod/github.com/!danny-!dasilva/utls@v0.0.0-20220604023528-30cb107b834e/conn.go:577
github.com/Danny-Dasilva/utls.(*Conn).Read(0xc020ab2380, {0xc00913e000, 0x1000, 0xc0393d7740?})
        C:/Users/snek/go/pkg/mod/github.com/!danny-!dasilva/utls@v0.0.0-20220604023528-30cb107b834e/conn.go:1257 +0x157
bufio.(*Reader).Read(0xc0393d76e0, {0xc023d43998, 0x9, 0xc035985ec0?})
        C:/Program Files/Go/src/bufio/bufio.go:237 +0x1bb
io.ReadAtLeast({0xf83020, 0xc0393d76e0}, {0xc023d43998, 0x9, 0x9}, 0x9)
        C:/Program Files/Go/src/io/io.go:332 +0x9a
io.ReadFull(...)
        C:/Program Files/Go/src/io/io.go:351
github.com/Danny-Dasilva/fhttp/http2.readFrameHeader({0xc023d43998?, 0x9?, 0xc00d4a54a0?}, {0xf83020?, 0xc0393d76e0?})
        C:/Users/snek/go/pkg/mod/github.com/!danny-!dasilva/fhttp@v0.0.0-20220524230104-f801520157d6/http2/frame.go:238 +0x6e
github.com/Danny-Dasilva/fhttp/http2.(*Framer).ReadFrame(0xc023d43960)
        C:/Users/snek/go/pkg/mod/github.com/!danny-!dasilva/fhttp@v0.0.0-20220524230104-f801520157d6/http2/frame.go:494 +0x95
github.com/Danny-Dasilva/fhttp/http2.(*clientConnReadLoop).run(0xc033631fa0)
        C:/Users/snek/go/pkg/mod/github.com/!danny-!dasilva/fhttp@v0.0.0-20220524230104-f801520157d6/http2/transport.go:2034 +0x165
github.com/Danny-Dasilva/fhttp/http2.(*ClientConn).readLoop(0xc0393ca340)
        C:/Users/snek/go/pkg/mod/github.com/!danny-!dasilva/fhttp@v0.0.0-20220524230104-f801520157d6/http2/transport.go:1956 +0x79
created by github.com/Danny-Dasilva/fhttp/http2.(*Transport).newClientConn
        C:/Users/snek/go/pkg/mod/github.com/!danny-!dasilva/fhttp@v0.0.0-20220524230104-f801520157d6/http2/transport.go:803 +0xe3f
```

**Comment by Icarohwq** [comment]
Did you manage to fix it?

**Comment by snekROmonoro** [comment]
> Did you manage to fix it?

nah but i saw it happens cuz of memory leaks

**Comment by Tanjhand** [comment]
> > 你修好了吗？
> 
> 不，但我看到它发生是因为内存泄漏

Have you solved it

**Comment by snekROmonoro** [comment]
> > > 你修好了吗？
> > 
> > 
> > 不，但我看到它发生是因为内存泄漏
> 
> Have you solved it

I stopped having this issue after some time, I am not sure exactly why it happened.
