### ISSUE TITLE
Run on Linux | Linux Support?

### ISSUE THREAD

**Issue by optionsx** [Danny-Dasilva/CycleTLS#243]
### Description

testing it on Kali Linux 64bit with golang and nodejs v18 installed

### Issue Type

Support

### Operating System

Linux

### Node Version

Other

### Golang Version

Other

### Relevant Log Output

```shell
Error Processing Request (please open an issue https://github.com/Danny-Dasilva/CycleTLS/issues/new/choose) -> /bin/sh: 1: /home/kali/Desktop/testing/node_modules/cycletls/dist/index: Permission denied

node:internal/errors:491
ErrorCaptureStackTrace(err);
^

Error: kill ESRCH
at process.kill (node:internal/process/per_thread:221:13)
at /home/kali/Desktop/testing/node_modules/cycletls/dist/index.js:59:25
at new Promise ()
at cleanExit (/home/kali/Desktop/testing/node_modules/cycletls/dist/index.js:58:13)
at Socket. (/home/kali/Desktop/testing/node_modules/cycletls/dist/index.js:86:19)
at Socket.emit (node:events:513:28)
at addChunk (node:internal/streams/readable:324:12)
at readableAddChunk (node:internal/streams/readable:297:9)
at Readable.push (node:internal/streams/readable:234:10)
at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
errno: -3,
code: 'ESRCH',
syscall: 'kill'
}

Node.js v18.13.0
```

**Comment by akshitdandyan** [comment]
Any updates on this? 
I am unable to run it in production (using a virtual machine and alpine image using Docker)
I get same error as mentioned above.
<img width="642" alt="image" src="https://github.com/Danny-Dasilva/CycleTLS/assets/70468471/9fe6e1b4-b925-45f7-a375-4be105f2ccb7">

**Comment by Danny-Dasilva** [comment]
It seems the package isn't being installed properly, how are you guys installing/running the package. The `/cycletls/dist/index` not found error means the package is either not installed or is not compiled correctly locally
