### ISSUE TITLE
Error Processing Request -> /home/ubuntu/project/node_modules/cycletls/dist/index-arm64: not found

### ISSUE THREAD

**Issue by WasimRehmn** [Danny-Dasilva/CycleTLS#255]
### Description

const {default : initCycleTLS} = require('cycletls');

(async () => {
  // Initiate CycleTLS
  const cycleTLS = await initCycleTLS();

  // Send request
  const response = await cycleTLS('https://ja3er.com/json', {
    body: '',
    ja3: '771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-51-57-47-53-10,0-23-65281-10-11-35-16-5-51-43-13-45-28-21,29-23-24-25-256-257,0',
    userAgent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0',
    proxy: 'http://username:password@hostname.com:443'
  }, 'get');

  console.log(response);

  // Cleanly exit CycleTLS
  cycleTLS.exit();

})();

### Issue Type

Bug, Support

### Operating System

Linux

### Node Version

Node 16.x

### Golang Version

None

### Relevant Log Output

```shell
Error Processing Request (please open an issue https://github.com/Danny-Dasilva/CycleTLS/issues/new/choose) -> /bin/sh: 1: /home/ubuntu/project/node_modules/cycletls/dist/index-arm64: not found

Error Processing Request (please open an issue https://github.com/Danny-Dasilva/CycleTLS/issues/new/choose) -> /bin/sh: 1: 
Error Processing Request (please open an issue https://github.com/Danny-Dasilva/CycleTLS/issues/new/choose) -> /home/ubuntu/project/node_modules/cycletls/dist/index-arm64: not found
Error Processing Request (please open an issue https://github.com/Danny-Dasilva/CycleTLS/issues/new/choose) -> /bin/sh: 1: /home/ubuntu/project/node_modules/cycletls/dist/index-arm64: not found

Error Processing Request (please open an issue https://github.com/Danny-Dasilva/CycleTLS/issues/new/choose) -> /bin/sh: 1: /home/ubuntu/project/node_modules/cycletls/dist/index-arm64: not found

node:internal/errors:478
    ErrorCaptureStackTrace(err);
    ^

Error: kill ESRCH
    at process.kill (node:internal/process/per_thread:221:13)
    at /home/ubuntu/project/node_modules/cycletls/dist/index.js:59:25
    at new Promise (<anonymous>)
    at cleanExit (/home/ubuntu/project/node_modules/cycletls/dist/index.js:58:13)
    at Socket.<anonymous> (/home/ubuntu/project/node_modules/cycletls/dist/index.js:86:19)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errno: -3,
  code: 'ESRCH',
  syscall: 'kill'
}
```

**Comment by Danny-Dasilva** [comment]
I changed how the binaries are compiled and read in, would you be able to re-test and let me know if the latest release fixed this

**Comment by Geczy** [comment]
i have this same issue @Danny-Dasilva 

```js
Error Processing Request (please open an issue https://github.com/Danny-Dasilva/CycleTLS/issues/new/choose) -> /bin/sh: /app/node_modules/cycletls/dist/index: not found

Error Processing Request (please open an issue https://github.com/Danny-Dasilva/CycleTLS/issues/new/choose) -> /bin/sh: /app/node_modules/cycletls/dist/index: not found

Error Processing Request (please open an issue https://github.com/Danny-Dasilva/CycleTLS/issues/new/choose) -> /bin/sh: /app/node_modules/cycletls/dist/index: not found

node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: kill ESRCH
    at process.kill (node:internal/process/per_thread:234:13)
    at /app/node_modules/cycletls/dist/index.js:59:25
    at new Promise (<anonymous>)
    at cleanExit (/app/node_modules/cycletls/dist/index.js:58:13)
    at Socket.<anonymous> (/app/node_modules/cycletls/dist/index.js:87:19)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
    at readableAddChunk (node:internal/streams/readable:349:9)
    at Readable.push (node:internal/streams/readable:286:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errno: -3,
  code: 'ESRCH',
  syscall: 'kill'
}

Node.js v20.9.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /opt/yarn-v1.22.19/lib/cli.js run docker:production
Directory: /app/packages/twitch/chat
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
Done in 1.47s.
```

**Comment by Geczy** [comment]
this is my server:

Linux ec2.internal amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jun 29 18:11:59 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Geczy** [comment]
another

```js
Error Processing Request (please open an issue https://github.com/Danny-Dasilva/CycleTLS/issues/new/choose) -> qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
Error: kill ESRCH
    at process.kill (node:internal/process/per_thread:234:13)
    at /app/node_modules/cycletls/dist/index.js:59:25
    at new Promise (<anonymous>)
    at cleanExit (/app/node_modules/cycletls/dist/index.js:58:13)
    at Socket.<anonymous> (/app/node_modules/cycletls/dist/index.js:87:19)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:376:12)
    at readableAddChunk (node:internal/streams/readable:349:9)
    at Socket.Readable.push (node:internal/streams/readable:286:10) {
  errno: -3,
  code: 'ESRCH',
  syscall: 'kill'
}
```

**Comment by Geczy** [comment]
i fixed the last issue with this placed in my dockerfile, but haven't tested if the first issue still exists

```
RUN apk add --no-cache libc6-compat
RUN ln -s /usr/x86_64-linux-gnu/lib64/ /lib64
```
