### ISSUE TITLE
centos 7.6    kill ESRCH

### ISSUE THREAD

**Issue by uuundefined** [Danny-Dasilva/CycleTLS#256]
### Description

kill ESRCHError: kill ESRCH
-bash: kill: ESRCHError:: arguments must be process or job IDs
-bash: kill: kill: arguments must be process or job IDs
-bash: kill: ESRCH: arguments must be process or job IDs
[root@No server_claudeAPI]#     at process.kill (node:internal/process/per_thread:221:13)
-bash: syntax error near unexpected token `('
[root@No server_claudeAPI]#     at /home/server_claudeAPI/node_modules/cycletls/dist/index.js:59:25
-bash: at: command not found
[root@No server_claudeAPI]#     at new Promise (<anonymous>)
-bash: syntax error near unexpected token `('
[root@No server_claudeAPI]#     at cleanExit (/home/server_claudeAPI/node_modules/cycletls/dist/index.js:58:13)
-bash: syntax error near unexpected token `('
[root@No server_claudeAPI]#     at Socket.<anonymous> (/home/server_claudeAPI/node_modules/cycletls/dist/index.js:86:19)
-bash: syntax error near unexpected token `('
[root@No server_claudeAPI]#     at Socket.emit (node:events:513:28)
-bash: syntax error near unexpected token `('
[root@No server_claudeAPI]#     at Socket.emit (node:domain:489:12)
-bash: syntax error near unexpected token `('
[root@No server_claudeAPI]#     at addChunk (node:internal/streams/readable:315:12)
-bash: syntax error near unexpected token `('
[root@No server_claudeAPI]#     at readableAddChunk (node:internal/streams/readable:289:9)
-bash: syntax error near unexpected token `('
[root@No server_claudeAPI]#     at Socket.Readable.push (node:internal/streams/readable:228:10)
-bash: syntax error near unexpected token `('
[root@No server_claudeAPI]#     at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
-bash: syntax error near unexpected token `('
[root@No server_claudeAPI]#   errno: -3,
-bash: errno:: command not found
[root@No server_claudeAPI]#   code: 'ESRCH',
-bash: code:: command not found
[root@No server_claudeAPI]#   syscall: 'kill'
-bash: syscall:: command not found
[root@No server_claudeAPI]# }

### Issue Type

Bug

### Operating System

Linux

### Node Version

Node 14.x

### Golang Version

None

### Relevant Log Output

```shell
kill ESRCHError: kill ESRCH
-bash: kill: ESRCHError:: arguments must be process or job IDs
-bash: kill: kill: arguments must be process or job IDs
-bash: kill: ESRCH: arguments must be process or job IDs
[root@No server_claudeAPI]#     at process.kill (node:internal/process/per_thread:221:13)
-bash: syntax error near unexpected token `('
[root@No server_claudeAPI]#     at /home/server_claudeAPI/node_modules/cycletls/dist/index.js:59:25
-bash: at: command not found
[root@No server_claudeAPI]#     at new Promise (<anonymous>)
-bash: syntax error near unexpected token `('
[root@No server_claudeAPI]#     at cleanExit (/home/server_claudeAPI/node_modules/cycletls/dist/index.js:58:13)
-bash: syntax error near unexpected token `('
[root@No server_claudeAPI]#     at Socket.<anonymous> (/home/server_claudeAPI/node_modules/cycletls/dist/index.js:86:19)
-bash: syntax error near unexpected token `('
[root@No server_claudeAPI]#     at Socket.emit (node:events:513:28)
-bash: syntax error near unexpected token `('
[root@No server_claudeAPI]#     at Socket.emit (node:domain:489:12)
-bash: syntax error near unexpected token `('
[root@No server_claudeAPI]#     at addChunk (node:internal/streams/readable:315:12)
-bash: syntax error near unexpected token `('
[root@No server_claudeAPI]#     at readableAddChunk (node:internal/streams/readable:289:9)
-bash: syntax error near unexpected token `('
[root@No server_claudeAPI]#     at Socket.Readable.push (node:internal/streams/readable:228:10)
-bash: syntax error near unexpected token `('
[root@No server_claudeAPI]#     at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
-bash: syntax error near unexpected token `('
[root@No server_claudeAPI]#   errno: -3,
-bash: errno:: command not found
[root@No server_claudeAPI]#   code: 'ESRCH',
-bash: code:: command not found
[root@No server_claudeAPI]#   syscall: 'kill'
-bash: syscall:: command not found
[root@No server_claudeAPI]# }
```

**Comment by uuundefined** [comment]
Error Processing Request (please open an issue https://github.com/Danny-Dasilva/CycleTLS/issues/new/choose) -> /bin/sh: /home/server_claudeAPI/node_modules/cycletls/dist/index: Permission denied

2023-08-06 15:07:30.548 cycletls:: child: 8296
/home/server_claudeAPI/claudeAPI.js:391
        throw(err);
        ^

Error: kill ESRCH

**Comment by uuundefined** [comment]
if (child) {
            //linux/darwin os
            new Promise((resolve, reject) => {
                process.kill(-child.pid);              //why    -child.pid?
                if (exit)
                    process.exit();
            });
        }

**Comment by Danny-Dasilva** [comment]
I would retry this with the latest release. It seems you're installing this with different permissions than you are running it. Try installing it for your user. 


Why -child.pid?: In POSIX systems (which include Linux and Darwin), providing a negative PID to process.kill sends the signal to all processes in the process group of the given PID. If you pass -child.pid, it sends the signal to the entire process group rather than just the child process. This is useful if the child process has spawned its own child processes and you want to terminate all of them. This is the case for CycleTLS which spawns a websocket server in golang
