### ISSUE TITLE
Error Processing Request

### ISSUE THREAD

**Issue by canyesilyurt** [Danny-Dasilva/CycleTLS#361]
### Description

Please give me example post and get request for javascript

### Issue Type

Support

### Operating System

Mac OS

### Node Version

Other

### Golang Version

None

### Relevant Log Output

```shell
Error Processing Request (please open an issue https://github.com/Danny-Dasilva/CycleTLS/issues/new/choose) 



node:internal/errors:563
    ErrorCaptureStackTrace(err);
    ^

Error: kill EPERM
    at process.kill (node:internal/process/per_thread:234:13)
    at /Users/cy/Downloads/kick aio s/jsfollow/node_modules/cycletls/dist/index.js:63:25
    at new Promise (<anonymous>)
    at cleanExit (/Users/cy/Downloads/kick aio s/jsfollow/node_modules/cycletls/dist/index.js:62:19)
    at Socket.<anonymous> (/Users/cy/Downloads/kick aio s/jsfollow/node_modules/cycletls/dist/index.js:91:19)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errno: -1,
  code: 'EPERM',
  syscall: 'kill'
}
```

**Comment by BungeeDesign** [comment]
I encountered the same issue. This error occurs when there's white space in your working directory path (in your case: `/kick aio s/`). To fix this, move your project to a directory path without spaces.

**Comment by ashishpipaliya** [comment]
I am facing the same issue. No file in my project contains white space in file name. Even my username is also single word name.

Still I face this error

```shell
Error: kill EPERM
    at process.kill (node:internal/process/per_thread:219:13)
    at /Users/neo/mynra-price-notifier/backend/node_modules/cycletls/dist/index.js:63:25
    at new Promise (<anonymous>)
    at cleanExit (/Users/neo/mynra-price-notifier/backend/node_modules/cycletls/dist/index.js:62:19)
    at Socket.<anonymous> (/Users/neo/mynra-price-notifier/backend/node_modules/cycletls/dist/index.js:91:19)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:189:23) {
  errno: -1,
  code: 'EPERM',
  syscall: 'kill'
}

Node.js v23.3.0
```
