### ISSUE TITLE
Client.Timeout or context cancellation while reading body

### ISSUE THREAD

**Issue by chrisebt** [Danny-Dasilva/CycleTLS#40]
**Actual behavior** A clear and concise description of what the bug is.

Hello, first of all thanks for this this repository!

I have an issue with the timeout handling. In my project I use proxies, which seem to be very slow sometimes.
Therefor I was looking forward to implementing the recently added timeout feature.

Occasionally I am encountering the following issue although I have defined a timeout parameter for the client:

`Error: 2021/08/17 06:13:09 Parse Bytesnet/http: request canceled (Client.Timeout or context cancellation while reading body)

    at Socket.<anonymous> (C:\xxxx\node_modules\cycletls\dist\index.js:67:33)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
Error: 2021/08/17 06:13:09 Request Failed: net/http: request canceled (Client.Timeout or context cancellation while reading body)

    at Socket.<anonymous> (C:\xxxx\node_modules\cycletls\dist\index.js:67:33)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)`

**Expected behavior** A clear and concise description of what you expected to
happen.

As adressed in #31  and recently added in your latest update. When using proxies, that are sometimes very slow I expected the request to timeout after the specific time, I set up. Most of the time it works. But sometimes the error occurs.

**To Reproduce** Steps to reproduce the behavior

`
async function test() {

const cycleTLS = await initCycleTLS();

const response = await cycleTLS("http://httpbin.org/delay/2", {
body: "",
ja3: "771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-51-57-47-53-10,0-23-65281-10-11-35-16-5-51-43-13-45-28-21,29-23-24-25-256-257,0",
userAgent: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0",
timeout: 1,
}, "get");

console.log(response.status);
cycleTLS.exit()
};
`
**Additional Information**

-   Operating System: Windows 10 @ cycletls@0.0.12
-   Node version:  Node.js v14.15.1
-   Golang version: go1.16.6 windows/amd64

**Comment by Danny-Dasilva** [comment]
@MaverickMCD the `timeout` param is the number of seconds before request times out. I added this in to catch actual timeout errors that occur when this is not set in Golang. 

 The example you provided is actually in a [test file](https://github.com/Danny-Dasilva/CycleTLS/blob/main/tests/timeout.test.ts) that I wrote and should be returning a `408`. 

If you run this in your environment you should get a return status of `408` and a timeout error in the body
```js

const initCycleTLS = require('cycletls');


(async () => {

    const cycleTLS = await initCycleTLS();

    const response = await cycleTLS("http://httpbin.org/delay/2", {
    body: "",
    ja3: "771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-51-57-47-53-10,0-23-65281-10-11-35-16-5-51-43-13-45-28-21,29-23-24-25-256-257,0",
    userAgent: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0",
    timeout: 1,
    }, "get");

    console.log(response.status); //Should be 408
    cycleTLS.exit()
})();
```
Let me know if this is not the case in your environment and I can further debug

------------------
The error you provided is what happens when your `timeout` setting exceeds an actual http timeout (this means your request actually timed out). I will add in a catch for this so it also returns a `408`. It was for this reason I added a default timeout of 7 seconds initially. 

-------------
A quick band aid until I add this is to increase your  timeout to something like 20 or 30 seconds in order to not error out.

**Comment by MaverickMCD** [comment]
The code example works fine in my environment. I do get an 408 response. 
It depends on the proxies, I couldn't prevent those timeouts so far in my project. 
I will increase the timeout parameter as you suggested for now and look forward to handling
actual http timeouts in the future.
Thank you!

**Comment by slotZero01** [comment]
Hi, I encounter a similar issue. I created an API that will request through cycleTls proxy. sometimes it returns this error
```
Error Processing Request (please open an issue https://github.com/Danny-Dasilva/CycleTLS/issues/new/choose) -> 2023/08/31 08:59:13 Parse Bytesnet/http: request canceled (Client.Timeout or context cancellation while reading body)

Error Processing Request (please open an issue https://github.com/Danny-Dasilva/CycleTLS/issues/new/choose) -> 2023/08/31 08:59:13 Request Failed: net/http: request canceled (Client.Timeout or context cancellation while reading body)
```

and my subsequent requests are getting stuck. do you know what's happened @Danny-Dasilva ?
Thanks

**Comment by Danny-Dasilva** [comment]
This error should no longer occur as timeouts are properly wrapped in 2.0



https://github.com/Danny-Dasilva/CycleTLS/pull/387
